#!/usr/bin/env python3
"""
GHA wrapper for curator-1337 agent

Invokes the curator agent to analyze skills and creates PRs with findings.
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

try:
    from anthropic import Anthropic
except ImportError:
    print("⚠️  Anthropic SDK not installed. Run: pip install anthropic")
    sys.exit(1)


def load_agent_prompt():
    """Load the curator agent definition"""
    agent_path = Path(__file__).parent / "agents" / "curator.md"
    return agent_path.read_text()


def load_skill(skill_name):
    """Load a skill file for analysis"""
    repo_root = Path(__file__).parent.parent.parent

    if skill_name == "rust-1337":
        skill_path = repo_root / "plugins" / "rust-1337" / "SKILL.md"
    elif skill_name == "terminal-1337":
        skill_path = repo_root / "plugins" / "terminal-1337" / "skills" / "SKILL.md"
    else:
        raise ValueError(f"Unknown skill: {skill_name}")

    return skill_path.read_text()


def analyze_skill(client, agent_prompt, skill_name, skill_content):
    """Invoke curator agent to analyze a skill"""
    print(f"\n🔍 Analyzing {skill_name}...")

    user_prompt = f"""Analyze the following skill for outdated recommendations:

# Skill: {skill_name}

{skill_content}

Provide your curator analysis following the structured format in your instructions."""

    response = client.messages.create(
        model="claude-sonnet-4-5-20250929",
        max_tokens=8192,
        system=agent_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )

    return response.content[0].text


def main():
    parser = argparse.ArgumentParser(description="Curator-1337 GHA wrapper")
    parser.add_argument(
        "--check",
        choices=["rust", "terminal", "all"],
        default="all",
        help="Skills to check",
    )
    parser.add_argument("--dry-run", action="store_true", help="Don't create PR")
    args = parser.parse_args()

    # Get API key
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("❌ ANTHROPIC_API_KEY not set")
        sys.exit(1)

    client = Anthropic(api_key=api_key)

    # Load curator agent
    print("📋 Loading curator agent...")
    agent_prompt = load_agent_prompt()

    # Analyze skills
    findings = []
    skills_to_check = []

    if args.check in ["rust", "all"]:
        skills_to_check.append("rust-1337")
    if args.check in ["terminal", "all"]:
        skills_to_check.append("terminal-1337")

    for skill_name in skills_to_check:
        skill_content = load_skill(skill_name)
        analysis = analyze_skill(client, agent_prompt, skill_name, skill_content)
        findings.append({"skill": skill_name, "analysis": analysis})

    # Generate summary
    print("\n" + "=" * 60)
    print(f"📊 CURATOR SUMMARY ({datetime.now().strftime('%Y-%m-%d %H:%M')})")
    print("=" * 60)

    has_findings = False
    for finding in findings:
        print(f"\n## {finding['skill']}\n")
        print(finding["analysis"])

        if "NO UPDATES NEEDED" not in finding["analysis"].upper():
            has_findings = True

    if not has_findings:
        print("\n✅ All skills remain best-in-class!")
        return

    # Create PR if not dry-run
    if not args.dry_run:
        print("\n📝 Creating findings document...")
        repo_root = Path(__file__).parent.parent.parent
        findings_path = repo_root / "curator-findings.md"

        findings_doc = f"# Curator-1337 Findings\n\n"
        findings_doc += f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}\n\n"

        for finding in findings:
            findings_doc += f"## {finding['skill']}\n\n"
            findings_doc += finding["analysis"] + "\n\n"
            findings_doc += "---\n\n"

        findings_doc += "*Generated by curator-1337 agent*\n"

        findings_path.write_text(findings_doc)
        print(f"✅ Findings written to {findings_path}")
        print("   GHA will create PR with these findings")
    else:
        print("\n🏃 Dry run mode - no PR created")


if __name__ == "__main__":
    main()
